// src/pages/passwords/forgot-password.jsx
import { Button, Divider, Form, Input } from 'tdesign-react'
import { CheckCircleFilledIcon, MailIcon } from 'tdesign-icons-react'
import { Link, useHistory } from 'react-router-dom'
import { useMutation } from 'react-query'
import { useRef } from 'react'
import OutsideLayout from '../../layouts/outside'
import reqres from '../../helpers/reqres'
// // import { If, Then, Else } from 'react-if'

export default function ForgotPasswordPage() {
  return (
    <OutsideLayout page={{ title: 'Forgot Password' }}>
      <div className="px-8 md:px-12 pt-10 pb-12">
        <div className="text-center mb-8">
          <h1 className="text-3xl mb-3">Forgot Password</h1>
          <p className="text-base">
            Enter your email to retrieve your password
          </p>
        </div>
        <Form>
          <Form.FormItem>
            <Input
              prefixIcon={<MailIcon />}
              placeholder="Email Address"
              size="large"
              type="email"
            />
          </Form.FormItem>
          <Form.FormItem>
            <Button block loading={false} size="large" type="submit">
              Retrieve Password
            </Button>
          </Form.FormItem>
        </Form>
        <Divider className="m-0">
          <Link className="text-base text-cyan-500" to="/login">
            Back to login page
          </Link>
        </Divider>
      </div>
    </OutsideLayout>
  )
}

//      <Result status="success" title="We have sent you a password recovery email." />
// <a-result status="success" title="We have sent you a password recovery email."></a-result>
// <a-form class="forgotPassword"
//       user: {
//         email: ''
//       },
//       success: false,
//       isLoading: false
// async forgotPassword() {
//     const { email } = this.user
//     const { data } = await axios.post('/api/send-reset-password', { email })
//     this.user.email = ''

// @src/pages/forgot-password.vue
<template>
  <outside-layout>
    <div class="bg-white shadow rounded px-12 py-8">
      <div v-if="success" class="max-w-sm">
        <a-result status="success" title="We have sent you a password recovery email."></a-result>
      </div>
      <template v-else>
        <div class="text-center mb-8">
          <h1 class="text-3xl">Forgot Password</h1>
          <p>Enter your email address to retrieve your password</p>
        </div>
        <a-form class="forgotPassword" :model="user" layout="vertical" @submit.prevent="forgotPassword">
          <a-form-item>
            <a-input v-model:value="user.email" placeholder="Email Address" size="large" type="email">
              <template #prefix>
                <MailOutlined class="mr-1" />
              </template>
            </a-input>
          </a-form-item>
          <a-form-item>
            <a-button block :loading="isLoading" html-type="submit" size="large" type="primary">Retrieve Password</a-button>
          </a-form-item>
        </a-form>
      </template>
      <a-divider>
        <router-link class="font-normal" to="/login">Back to login page</router-link>
      </a-divider>
    </div>
  </outside-layout>
</template>

<script>
import axios from 'axios'
import { message } from 'ant-design-vue'
import { MailOutlined } from '@ant-design/icons-vue'
import OutsideLayout from '../layouts/outside.vue'
import head from '../plugins/head'

export default {
  components: {
    MailOutlined,
    OutsideLayout
  },
  data() {
    return {
      user: {
        email: ''
      },
      success: false,
      isLoading: false
    }
  },
  methods: {
    async forgotPassword() {
      this.isLoading = true
      try {
        const { email } = this.user
        const { data } = await axios.post('/api/send-reset-password', { email })
        this.user.email = ''
        this.success = true
      } catch ({ response }) {
        message.error(response.data.message)
      } finally {
        this.isLoading = false
      }
    }
  },
  beforeCreate() {
    head.title('Forgot Password')
  },
  async created() {
    try {
      await axios.delete('/api/logout')
    } catch ({ response }) {
      if (window.sanctum) {
        message.error(response.data.message)
      }
    }
  }
}
</script>

<style scoped>
form.forgotPassword {
  width: 24rem;
}
</style>
