// src/pages/login.tsx
import { Button, Card, Divider, Form, Input, message as toast } from 'antd'
import { UserOutlined, LockOutlined } from '@ant-design/icons'
import { Link, useHistory } from 'react-router-dom'
// import { useMutation } from 'react-query'
import { useRef } from 'react'
import { PageLayout } from '../layouts/page'
// import reqres from '../helpers/reqres'

export default function LoginPage() {
  const form = useRef()
  const history = useHistory()
  // const { isLoading, mutate } = useMutation(
  //   (account) => reqres.login(account),
  //   {
  //     onSuccess: (data) => handleSuccess(data),
  //     onError: ({ response }) => showError(response?.data?.error)
  //   }
  // )

  // function handleSubmit(event) {
  //   const { email, password } = form.current.getFieldsValue([
  //     'email',
  //     'password'
  //   ])
  //   mutate({ email, password })
  // }

  function handleSuccess(data) {
    history.replace('/')
  }

  function showError(message = '使用者名称或密码错误') {
    toast.error(message)
  }

  return (
    <PageLayout page={{ title: 'Log In' }}>
      <Card>asdasdsd</Card>
      <div className="max-w-md mx-auto rounded shadow bg-white">
        <div className="px-8 md:px-12 pt-10 pb-12">
        <h1 className="text-3xl text-center mb-8">Welcome Back</h1>
          <Form ref={form}>
            <Form.Item name="email">
              <Input
                prefix={<UserOutlined className="w-4 h-4" />}
                placeholder="Email Address"
                size="large"
              />
            </Form.Item>
            <Form.Item name="password">
              <Input
                prefix={<LockOutlined className="w-4 h-4" />}
                placeholder="Password"
                size="large"
                type="password"
              />
            </Form.Item>
            <Form.Item>
              <Button className="bg-black" block loading={false} type="primary" size="large">
                Log In
              </Button>
            </Form.Item>
          </Form>
          <Divider>
            <Link className="text-base text-cyan-500" to="/forgot-password">
              Forgot your password?
            </Link>
          </Divider>
        </div>
      </div>
    </PageLayout>
  )
}

// @src/pages/login.vue
<template>
  <outside-layout>
    <div class="bg-white shadow rounded px-12 py-8">
      <div class="text-center mb-8">
        <h1 class="text-3xl">Welcome Back</h1>
      </div>
      <a-form class="login" :model="user" layout="vertical" @submit.prevent="login">
        <a-form-item>
          <a-input v-model:value="user.email" required placeholder="Email Address" size="large" type="email">
            <template #prefix>
              <UserOutlined class="mr-1" />
            </template>
          </a-input>
        </a-form-item>
        <a-form-item>
          <a-input v-model:value="user.password" required placeholder="Password" size="large" type="password">
            <template #prefix>
              <LockOutlined class="mr-1" />
            </template>
          </a-input>
          <div class="flex justify-end">
            <router-link class="leading-10" to="/forgot-password">Forgot your password?</router-link>
          </div>
        </a-form-item>
        <a-form-item>
          <a-button block :loading="isLoading" html-type="submit" size="large" type="primary">Log In</a-button>
        </a-form-item>
      </a-form>
    </div>
  </outside-layout>
</template>

<script>
import axios from 'axios'
import { message } from 'ant-design-vue'
import { UserOutlined, LockOutlined } from '@ant-design/icons-vue'
import OutsideLayout from '../layouts/outside.vue'
import head from '../plugins/head'

export default {
  components: {
    UserOutlined,
    LockOutlined,
    OutsideLayout
  },
  data() {
    return {
      user: {
        email: '',
        password: ''
      },
      isLoading: false
    }
  },
  methods: {
    async login() {
      this.isLoading = true
      try {
        const { email, password } = this.user
        const { data } = await axios.post('/api/login', { email, password, remember: 'on' })
        axios.defaults.headers.common['Authorization'] = `Bearer ${data.access_token}`
        this.$router.replace('/')
      } catch ({ response }) {
        message.error(response.data.message)
      } finally {
        this.isLoading = false
      }
    }
  },
  beforeCreate() {
    head.title('Log In')
  },
  async created() {
    try {
      await axios.delete('/api/logout')
    } catch ({ response }) {
      if (window.sanctum) {
        message.error(response.data.message)
      }
    }
  }
}
</script>

<style scoped>
form.login {
  width: 24rem;
}
</style>
