// src/pages/passwords/reset-password.tsx
import { LockOutlined } from '@ant-design/icons'
import { PageLayout } from '../../layouts/page'
import { useParams } from 'react-router-dom'
import { Button, Form, Input } from 'antd'

export default function ResetPasswordPage() {
  const { token } = useParams<{ token: string }>()

  return (
    <PageLayout page={{ title: 'Reset Password' }}>
      <div className="px-8 md:px-12 pt-10 pb-12">
        <h1 className="text-3xl text-center mb-8">Reset Password</h1>
        <Form>
          <Form.Item>
            <Input
              prefix={<LockOutlined />}
              placeholder="Password"
              size="large"
              type="password"
            />
          </Form.Item>
          <Form.Item>
            <Input
              prefix={<LockOutlined />}
              placeholder="Password Confirmation"
              size="large"
              type="password"
            />
          </Form.Item>
          <Form.Item>
            <Button block loading={false} size="large">
              Submit
            </Button>
          </Form.Item>
        </Form>
      </div>
    </PageLayout>
  )
}

// @src/pages/reset-password.vue
<template>
  <outside-layout>
    <div class="bg-white shadow rounded px-12 py-8">
      <div class="text-center mb-8">
        <h1 class="text-3xl">Reset Password</h1>
      </div>
      <a-form class="resetPassword" :model="user" layout="vertical" @submit.prevent="resetPassword">
        <a-form-item>
          <a-input v-model:value="user.password" placeholder="Password" size="large" type="password"></a-input>
        </a-form-item>
        <a-form-item>
          <a-input v-model:value="user.passwordConfirmation" placeholder="Password Confirmation" size="large" type="password"></a-input>
        </a-form-item>
        <a-form-item>
          <a-button block :loading="isLoading" html-type="submit" size="large" type="primary">Submit</a-button>
        </a-form-item>
      </a-form>
    </div>
  </outside-layout>
</template>

<script>
import axios from 'axios'
import { message } from 'ant-design-vue'
import OutsideLayout from '../layouts/outside.vue'
import head from '../plugins/head'

export default {
  components: {
    OutsideLayout
  },
  data() {
    return {
      user: {
        password: '',
        passwordConfirmation: ''
      },
      isLoading: false
    }
  },
  methods: {
    async resetPassword() {
      this.isLoading = true
      try {
        const { email } = this.$route.query
        const { token } = this.$route.params
        const { password: newPassword, passwordConfirmation } = this.user
        await axios.put('/api/reset-password', { email, token, newPassword, password_confirmation: passwordConfirmation })
        this.user = {
          password: '',
          passwordConfirmation: ''
        }
      } catch ({ response }) {
        message.error(response.data.message)
      } finally {
        this.isLoading = false
      }
    }
  },
  beforeCreate() {
    head.title('Reset Password')
  },
  async created() {
    try {
      await axios.delete('/api/logout')
    } catch ({ response }) {
      if (window.sanctum) {
        message.error(response.data.message)
      }
    }
  }
}
</script>

<style scoped>
form.resetPassword {
  width: 24rem;
}
</style>
